In [36]:
# Import numpy and pandas
import numpy as np
import pandas as pd
# Import operating specific functionality
import os

In [37]:
# Create variable "data" containing the data from the voice.csv file
data = pd.read_csv("voice.csv")

In [38]:
# Show the head of the data, confirming that the data is read and that we have all columns
data.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [39]:
# Convert the label from text male/female to binary value of 1 or 0
data.label = [1 if each == "male" else 0 for each in  data.label]
# Show head of data to confirm that label value is changed
data.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000      1  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632      1  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512      1  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119      1  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274      1  

[5 rows x 21 columns]

In [40]:
# Set variable "gender" to be the label column
gender = data.label
# Drop the label column from the data so that we now have features and labels separated
data.drop(["label"], axis = 1, inplace = True)


In [41]:
#Normalize the data to ensure that differing magnitude within features does not create a problem when running the model
data = (data-np.min(data))/(np.max(data)-np.min(data))

# Set variable "features" to be the normalized data
features = data

features.head()

meanfreq        sd    median       Q25       Q75       IQR      skew  \
0  0.096419  0.473409  0.084125  0.060063  0.204956  0.254828  0.367853   
1  0.125828  0.505075  0.116900  0.077635  0.215683  0.246961  0.644279   
2  0.179222  0.675536  0.102873  0.034284  0.385912  0.457148  0.885255   
3  0.528261  0.554611  0.587559  0.389906  0.715802  0.407358  0.031549   
4  0.452195  0.627209  0.454272  0.317627  0.707515  0.474474  0.027742   

       kurt    sp.ent       sfm      mode  centroid   meanfun    minfun  \
0  0.208279  0.635798  0.564526  0.000000  0.096419  0.157706  0.030501   
1  0.483766  0.630964  0.591578  0.000000  0.125828  0.287642  0.031140   
2  0.782275  0.442738  0.548382  0.000000  0.179222  0.236945  0.030264   
3  0.001613  0.923261  0.856457  0.299565  0.528261  0.183442  0.041287   
4  0.001732  0.958736  0.926348  0.372362  0.452195  0.279190  0.036829   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  
0  0.981526  0.000000  0.006452  0.000000  0.000000  0.000000  
1  0.834600  0.000407  0.006452  0.002144  0.002146  0.056449  
2  0.954963  0.000060  0.006452  0.000357  0.000358  0.049885  
3  0.834600  0.065659  0.006452  0.025375  0.025393  0.265043  
4  0.929285  0.238994  0.006452  0.250536  0.250715  0.223380

In [42]:
# Import train_test_split function from scikit-learn
from sklearn.model_selection import train_test_split

# Split data into training set and testing set with a test size of 20% of the samples.
# The integer 42 is used for shuffling the data
x_train, x_test, y_train, y_test = train_test_split(features, gender, test_size = 0.2, random_state = 42)

In [43]:
# Import cross validation
from sklearn.model_selection import cross_val_predict
# Import KNN
from sklearn.neighbors import KNeighborsClassifier
# Import confusion matrix
from sklearn.metrics import confusion_matrix

K_Optimal = 0
best_youden = 0
youden_scores = []

for K in range(1, 16):
    # Create a KNN model
    knn = KNeighborsClassifier(n_neighbors = K)
    # Train the  model with a cross validation value of 5
    y_train_pred = cross_val_predict(knn, x_train, y_train, cv = 5)
    print("Confusion Matrix for K of {}".format(K))
    print(confusion_matrix(y_train, y_train_pred))
    tn, fp, fn, tp = confusion_matrix(y_train, y_train_pred).ravel()
    print("tn: {}, fp: {}, fn: {}, tp: {}".format(tn, fp, fn, tp))
    sens = tp / (tp + fn)
    spec = tn / (fp + tn)
    youden = sens - (1 - spec)
    if best_youden < youden:
        best_youden = youden
        K_Optimal = K
        

# Print the optimal K vallue and it's accuracy
print("The optimal K value is {} with a Youden Index of {}".format(K_Optimal, best_youden))


Confusion Matrix for K of 1
[[1254   33]
 [  29 1218]]
tn: 1254, fp: 33, fn: 29, tp: 1218
Confusion Matrix for K of 2
[[1274   13]
 [  54 1193]]
tn: 1274, fp: 13, fn: 54, tp: 1193
Confusion Matrix for K of 3
[[1257   30]
 [  29 1218]]
tn: 1257, fp: 30, fn: 29, tp: 1218
Confusion Matrix for K of 4
[[1265   22]
 [  45 1202]]
tn: 1265, fp: 22, fn: 45, tp: 1202
Confusion Matrix for K of 5
[[1250   37]
 [  29 1218]]
tn: 1250, fp: 37, fn: 29, tp: 1218
Confusion Matrix for K of 6
[[1259   28]
 [  35 1212]]
tn: 1259, fp: 28, fn: 35, tp: 1212
Confusion Matrix for K of 7
[[1248   39]
 [  25 1222]]
tn: 1248, fp: 39, fn: 25, tp: 1222
Confusion Matrix for K of 8
[[1254   33]
 [  32 1215]]
tn: 1254, fp: 33, fn: 32, tp: 1215
Confusion Matrix for K of 9
[[1245   42]
 [  26 1221]]
tn: 1245, fp: 42, fn: 26, tp: 1221
Confusion Matrix for K of 10
[[1249   38]
 [  36 1211]]
tn: 1249, fp: 38, fn: 36, tp: 1211
Confusion Matrix for K of 11
[[1243   44]
 [  32 1215]]
tn: 1243, fp: 44, fn: 32, tp: 1215
Confusio